---
- hosts: db
  gather_facts: false
#  ignore_errors: 1
  tasks:
        - name: Check the date
          command: date2030
          ignore_errors: 1
        - name: Check the uptime
          command: 
                  uptime
                  date
                  nproc
                  lscpu
                  pwd


          